name = "G-Craft"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89cbb51b293568d52aa7d8d5906dd79b94c1d9cf76d7f9287fa4ba0ee8b13f65"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
