name = "G-Craft"
author = "Hikiru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22a14d76c902f21cb2523a68c0f00a1d4f5188eade075ef4394dbd6a9153b2ec"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
