name = "G-Craft"
author = "Hikiru"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24062a42d0d937a30371a9389f9ea5fd43ea81c18e3865c3e82a23da7ba97e0b"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
